//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brick_game.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brick_game.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string BBack {
            get {
                return ResourceManager.GetString("BBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základní nastavení.
        /// </summary>
        public static string BDefault {
            get {
                return ResourceManager.GetString("BDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Černá.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modrá.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string BSave {
            get {
                return ResourceManager.GetString("BSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec.
        /// </summary>
        public static string ButtonEnd {
            get {
                return ResourceManager.GetString("ButtonEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlevo.
        /// </summary>
        public static string ButtonLeft {
            get {
                return ResourceManager.GetString("ButtonLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vpravo.
        /// </summary>
        public static string ButtonRight {
            get {
                return ResourceManager.GetString("ButtonRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otoč.
        /// </summary>
        public static string ButtonRotate {
            get {
                return ResourceManager.GetString("ButtonRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauza.
        /// </summary>
        public static string ButtonStart_pause {
            get {
                return ResourceManager.GetString("ButtonStart_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barvy.
        /// </summary>
        public static string GBColors {
            get {
                return ResourceManager.GetString("GBColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozměry hrací plochy.
        /// </summary>
        public static string GBGameboardSize {
            get {
                return ResourceManager.GetString("GBGameboardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikost čtverečku.
        /// </summary>
        public static string GBSquareSize {
            get {
                return ResourceManager.GetString("GBSquareSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rychlost pádu.
        /// </summary>
        public static string GBStartSpeed {
            get {
                return ResourceManager.GetString("GBStartSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejlepších 5.
        /// </summary>
        public static string GBTopScores {
            get {
                return ResourceManager.GetString("GBTopScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šedá.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelená.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec hry.
        /// </summary>
        public static string LabelGameOver {
            get {
                return ResourceManager.GetString("LabelGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skóre: .
        /// </summary>
        public static string LabelScore {
            get {
                return ResourceManager.GetString("LabelScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostky:.
        /// </summary>
        public static string LBrickColor {
            get {
                return ResourceManager.GetString("LBrickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadej jméno: .
        /// </summary>
        public static string LEnterName {
            get {
                return ResourceManager.GetString("LEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrací plocha:.
        /// </summary>
        public static string LGBColor {
            get {
                return ResourceManager.GetString("LGBColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mřížka:.
        /// </summary>
        public static string LGridColor {
            get {
                return ResourceManager.GetString("LGridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výška:.
        /// </summary>
        public static string LHeight {
            get {
                return ResourceManager.GetString("LHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikost: .
        /// </summary>
        public static string LSquareSize {
            get {
                return ResourceManager.GetString("LSquareSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rychlost:.
        /// </summary>
        public static string LStartSpeed {
            get {
                return ResourceManager.GetString("LStartSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šířka:.
        /// </summary>
        public static string LWidth {
            get {
                return ResourceManager.GetString("LWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemáte nastavenou barvu. Nahrát standartní barvy?.
        /// </summary>
        public static string MBMissingColor {
            get {
                return ResourceManager.GetString("MBMissingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chybí barva.
        /// </summary>
        public static string MBMissingColorHead {
            get {
                return ResourceManager.GetString("MBMissingColorHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat všechna nejvyšší skóre?.
        /// </summary>
        public static string MBResetScores {
            get {
                return ResourceManager.GetString("MBResetScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu?.
        /// </summary>
        public static string MBResetScoresCaption {
            get {
                return ResourceManager.GetString("MBResetScoresCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrací plocha a kostky nesmí mít stejnou barvu!.
        /// </summary>
        public static string MBSameColors {
            get {
                return ResourceManager.GetString("MBSameColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Konec.
        /// </summary>
        public static string MIEnd {
            get {
                return ResourceManager.GetString("MIEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hra.
        /// </summary>
        public static string MIGame {
            get {
                return ResourceManager.GetString("MIGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ná_pověda.
        /// </summary>
        public static string MIHelp {
            get {
                return ResourceManager.GetString("MIHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použij šipky (Nahoru pro otočení).
        /// </summary>
        public static string MIHelpMessage {
            get {
                return ResourceManager.GetString("MIHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Nová hra.
        /// </summary>
        public static string MINewGame {
            get {
                return ResourceManager.GetString("MINewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Možnosti.
        /// </summary>
        public static string MIOptions {
            get {
                return ResourceManager.GetString("MIOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat nejvyšší skóre.
        /// </summary>
        public static string MIResetScores {
            get {
                return ResourceManager.GetString("MIResetScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N_astavení.
        /// </summary>
        public static string MISettings {
            get {
                return ResourceManager.GetString("MISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oranžová.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Růžová.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fialová.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Červená.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové skóre.
        /// </summary>
        public static string WEnterNameTitle {
            get {
                return ResourceManager.GetString("WEnterNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bílá.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení hry.
        /// </summary>
        public static string WSettingsTitle {
            get {
                return ResourceManager.GetString("WSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žlutá.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
