//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brick_game.Properites {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brick_game.Properites.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpet.
        /// </summary>
        internal static string BBack {
            get {
                return ResourceManager.GetString("BBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základní nastavení.
        /// </summary>
        internal static string BDefault {
            get {
                return ResourceManager.GetString("BDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        internal static string BSave {
            get {
                return ResourceManager.GetString("BSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec.
        /// </summary>
        internal static string ButtonEnd {
            get {
                return ResourceManager.GetString("ButtonEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlevo.
        /// </summary>
        internal static string ButtonLeft {
            get {
                return ResourceManager.GetString("ButtonLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vpravo.
        /// </summary>
        internal static string ButtonRight {
            get {
                return ResourceManager.GetString("ButtonRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otoč.
        /// </summary>
        internal static string ButtonRotate {
            get {
                return ResourceManager.GetString("ButtonRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauza.
        /// </summary>
        internal static string ButtonStart_pause {
            get {
                return ResourceManager.GetString("ButtonStart_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozměry hrací plochy.
        /// </summary>
        internal static string GBGameboardSize {
            get {
                return ResourceManager.GetString("GBGameboardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikost čtverečku.
        /// </summary>
        internal static string GBSquareSize {
            get {
                return ResourceManager.GetString("GBSquareSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rychlost pádu.
        /// </summary>
        internal static string GBStartSpeed {
            get {
                return ResourceManager.GetString("GBStartSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec hry.
        /// </summary>
        internal static string LabelGameOver {
            get {
                return ResourceManager.GetString("LabelGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skóre: .
        /// </summary>
        internal static string LabelScore {
            get {
                return ResourceManager.GetString("LabelScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výška:.
        /// </summary>
        internal static string LHeight {
            get {
                return ResourceManager.GetString("LHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikost: .
        /// </summary>
        internal static string LSquareSize {
            get {
                return ResourceManager.GetString("LSquareSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rychlost:.
        /// </summary>
        internal static string LStartSpeed {
            get {
                return ResourceManager.GetString("LStartSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šířka:.
        /// </summary>
        internal static string LWidth {
            get {
                return ResourceManager.GetString("LWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Konec.
        /// </summary>
        internal static string MIEnd {
            get {
                return ResourceManager.GetString("MIEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hra.
        /// </summary>
        internal static string MIGame {
            get {
                return ResourceManager.GetString("MIGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ná_pověda.
        /// </summary>
        internal static string MIHelp {
            get {
                return ResourceManager.GetString("MIHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použij šipky (Nahoru pro otočení).
        /// </summary>
        internal static string MIHelpMessage {
            get {
                return ResourceManager.GetString("MIHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Nová hra.
        /// </summary>
        internal static string MINewGame {
            get {
                return ResourceManager.GetString("MINewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N_astavení.
        /// </summary>
        internal static string MISettings {
            get {
                return ResourceManager.GetString("MISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení hry.
        /// </summary>
        internal static string WSettingsTitle {
            get {
                return ResourceManager.GetString("WSettingsTitle", resourceCulture);
            }
        }
    }
}
